### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by harpratap** [Gotham25/Hotstar-Video-Download#1]
Not really familiar with PHP. Is this a chrome extension? Or you run this locally? How do I use this to  watch videos on hotstar?

**Comment by Gotham25** [comment]
It's for downloading Hotstar videos through web ui not watching. Paste the video URL and then hit generate video and you have the video link generated. Added site url in readme file.

Note premium contents and few videos can't be downloaded. Hence it would show as unavailable or error.
