### ISSUE TITLE
The video I tried could not be downloaded

### ISSUE THREAD

**Issue by aadarsh2** [Gotham25/Hotstar-Video-Download#2]
https://www.hotstar.com/sports/football/arsenal-vs-liverpool/2001707928

I was actually trying to download this video but it shows the error, "Video not found in the playlist"
Is there any possible way to download this video?

**Comment by Gotham25** [comment]
The video is ### **DRM Protected.** So it's not possible to download it using any video downloaders. I'll create a PR for showing correct error messages like this. As of now it's incorrect.
