### ISSUE TITLE
Error in fetching the video format

### ISSUE THREAD

**Issue by DedSec002** [Gotham25/Hotstar-Video-Download#9]
Your hosted site can able to download the file.. but not from my end..

Do i need to change any configuration?

https://www.hotstar.com/sports/cricket/vivo-ipl-2019/sunrisers-hyderabad-vs-kolkata-knight-riders-m190291/match-clips/dominant-srh-swat-aside-kkr/2001629933?utm_source=onebox&utm_campaign=IPL19&utm_content=highlights

**Comment by Gotham25** [comment]
IE has some issues displaying the site. Chrome works fine as far as I know. Can you try again after clearing/disabling the cache ?.

If it doesn't work, can you post back here with a error screenshot ?. So that I can look after the same

**Comment by DedSec002** [comment]
Hi Gotham,

Thx for your response..

I use XAMPP server.

Can these files used on this localhost server?

Do i need to do something different in terms of server setup online or localhost.

Please have a section about installation.

Thank you

**Comment by Gotham25** [comment]
Hey,
Sorry for the delayed response. I was busy with something else.

Btw, I get it now what you're trying to do. I have to resolve some of the dependencies apart from the ones installed by composer locally to test out whether it's running fine.

I'll then have the same documented in a separate section. I'll have this done maybe within this weekend by end of next week.

Meanwhile, feel free to the site on which this is hosted.

**Comment by Gotham25** [comment]
@DedSec002 Hey. Can you try running the project in local and let me know what issues that you face in ?.
There are couple of environment variable you need optionally for uploading files to cloud. But right now this setup should work as long as you're connected to internet.

**Comment by roshan9227** [comment]
Hello Gotham

From today I am not able to select the format after copying the Hotstar Video Url. Till yesterday after copying the url there was an option to select the video format and thereby download it. I really need your help. I tried in every browser.its not working.
Kindly help me.

**Comment by roshan9227** [comment]
For reference I have attached a snapshot.
<img width="328" alt="Screen Shot 2019-07-04 at 6 52 20 PM" src="https://user-images.githubusercontent.com/52546280/60689591-10be6000-9e8d-11e9-996d-6c634b5aef84.png">

**Comment by sunnyrty** [comment]
not working again

**Comment by roshan9227** [comment]
@sunnyrty 
 Are you facing the same view format problem?

**Comment by roshan9227** [comment]
The video format problem?

**Comment by sunnyrty** [comment]
@roshan9227  yes same problem

hotstar changed lot

**Comment by Gotham25** [comment]
@roshan9227 Can you ping me the URL for which you face error ?. I'll have a look at it in backend.

**Comment by roshan9227** [comment]
The ability to choose video format is not working for any URL in Hotstar website.whenever I tried copying and pasting different URL,after clicking fetch video there is no option to select the different formats. Two days before there was option to select formats like 360p, 720p through a drop down menu. Now the drop down is not working.
Gotham,
Can you please see to it and rectify it. 
It would be great help for users like me.
Thank You

**Comment by roshan9227** [comment]
Gotham

Can you please see to the issue and kindly rectify it.

Regards

**Comment by Gotham25** [comment]
@roshan9227 : I have a PR as a quick fix to this issue. But I need to add a feature to have dash along with m3u8 formats too. So, Can you create a separate issue mentioning to add dash formats too ?.

**Comment by roshan9227** [comment]
Thanks a ton Gotham.

**Comment by roshan9227** [comment]
Hi Gotham

There as occurred an issue in generation of video after pasting url from
hotstar. Now all the formats are available but after pasting the url and
selection of format, the video is stuck in 0% without the generation of
video. This started today. Till yesterday it was working perfectly.

**Comment by Gotham25** [comment]
Hi,

I wonder how it fetched the formats itself. After the last fix I did, most
of the requests are Geo restricted. Which means when the server tries to
send any request to hotstar would result in access denied scenario. Unless
the servers are in India.

But anyways, the cause of the issue you're facing is due to pusher API
limit exceeded. I need to see some other alternatives for sending messages
from server to client.

Give me some time, I'll come back to you with an alternative solution.

Further on, If you have any issues, please do raise it in Github.

Regards
Gowtham
